CREATE DATABASE spa
    DEFAULT CHARACTER SET utf8;
USE spa;

CREATE TABLE products(
  id INT NOT NULL AUTO_INCREMENT UNIQUE,
  name VARCHAR(255) NOT NULL,
  image VARCHAR(255) NOT NULL,
  small_image VARCHAR(255) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  description TEXT CHARACTER SET utf8 NOT NULL,
  small_description TEXT CHARACTER SET utf8 NOT NULL
);
